swagger: "2.0"
info:
  description: "This document defines the openbexi timeline REST API specification."
  version: "1.0.0"
  title: "openbexi timeline"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "arcazj@gmail.com"
  license:
    name: "GNU General Public License v3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
host: "openbexi_timeline.swagger.io"
basePath: ""
tags:
  - name: "sessions"
    description: "Everything about your sessions"
schemes:
  - "https"
paths:
  /sessions/{startDate}/{endDate}/{filter}/{search}/{userAccess}:
    get:
      tags:
        - Sessions
      summary: Get sessions by Zone
      description: Return sessions between the startDate and endDate
      operationId: getSessionByZone
      produces:
        - application/json
      parameters:
        - name: startDate
          in: path
          description: Start date
          required: true
          type: string
          format: date-time
        - name: endDate
          in: path
          description: End date
          required: true
          type: string
          format: date-time
        - name: filter
          in: path
          description: filter events
          required: true
          type: string
          format: string
        - name: search
          in: path
          description: search events
          required: true
          type: string
          format: string
        - name: userAccess
          in: path
          description: user permission to add,update,delete events
          required: true
          type: string
          format: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Object'
        "400":
          description: Invalid input

  /sessions/{events}/{userAccess}:
    post:
      tags:
        - Sessions
        summary: Add or update events
        description: Add new events or update existing events regarding user access
        operationId: updateEvents
        produces:
          - application/json
      parameters:
        - name: startDate
          in: path
          description: Start date
          required: true
          type: string
          format: date-time
        - name: endDate
          in: path
          description: End date
          required: true
          type: string
          format: date-time
        - name: userAccess
          in: path
          description: user permission to add,update,delete events
          required: true
          type: string
          format: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Object'
        "400":
          description: Invalid input

  /sessions/{events}/{userAccess}:
    delete:
      tags:
        - Sessions
      summary: Delete events
      description: Delete existing events regarding user access
      operationId: deleteEvents
      produces:
        - application/json
      parameters:
        - name: startDate
          in: path
          description: Start date
          required: true
          type: string
          format: date-time
        - name: endDate
          in: path
          description: End date
          required: true
          type: string
          format: date-time
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Object'
        "400":
          description: Invalid input

securityDefinitions:
  sessionstore_auth:
    type: "oauth2"
    authorizationUrl: "https://localhost:8443/"
    flow: "implicit"
    scopes:
      write:sessions: "modify sessions in your account"
      read:sessions: "read your sessions"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Json:
    type: object
    required:
      - Incompatible
      - name
    properties:
      name:
        type: string
      Incompatible:
        type: boolean
        default: false
  Obj:
    type: object
    required:
      - startDate
    properties:
      current time:
        type: string
        format: date
      spacecraft:
        type: integer
        format: int64
      startDate:
        type: string
        format: date
      latestEnd:
        type: string
        format: date
  Param:
    type: object
    required:
      - date
      - message
    properties:
      date:
        type: string
        format: date
      message:
        type: string
  json:
    type: object
    required:
      - startDate
    properties:
      type:
        type: string
      priority:
        type: string
      spacecraft:
        type: integer
        format: int64
      startDate:
        type: string
        format: date
      latestEnd:
        type: string
        format: date
      duration:
        type: string
      tolerance:
        type: string
      switch overtime:
        type: string
      interval:
        type: string
      measurmentCount:
        type: string
      measurement total:
        type: string
  Object:
    type: object
    required:
      - startDate
    properties:
      id:
        type: integer
        format: int64
      type:
        type: string
      label:
        type: string
        format: ""
      spacecraft:
        type: integer
        format: int64
      startDate:
        type: string
        format: date
      template:
        type: string
      measurmentType:
        type: string
      measurmentCount:
        type: string
      procLanuage:
        type: string
      terminateBefore:
        type: string
  object:
    type: object
    required:
      - startDate
    properties:
      type:
        type: string
      label:
        type: string
        format: ""
      spacecraft:
        type: integer
        format: int64
      startDate:
        type: string
        format: date
      template:
        type: string
      measurmentType:
        type: string
      measurmentCount:
        type: string
      procLanuage:
        type: string
      terminateBefore:
        type: string
  ApiResponse:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
externalDocs:
  description: Find out more
  url: https://github.com/arcazj/openbexi_timeline