package com.openbexi.timeline.data_browser;

import com.mongodb.MongoException;
import com.mongodb.client.*;
import org.bson.Document;
import org.bson.types.ObjectId;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

//This class uses OpenAI's GPT models for language processing and has been generated by ChatGPT4.
public class db_mongo_manager extends data_manager {

    private MongoDatabase _database;
    private MongoCollection<Document> _collection;

    public db_mongo_manager(String currentStartDate, String currentEndDate, String search,
                            String filter, String action_type, HttpServletResponse response, HttpSession session, data_configuration configuration) {
        super(response, session, configuration);

        login(configuration.getUrl(0), configuration.getDatabase(0), configuration.getCollection(0), null);
        get_filter();
    }

    /** Uses an already authenticated collection, including in isolated adapter tests. */
    db_mongo_manager(MongoCollection<Document> collection, data_configuration configuration) {
        super(null, null, configuration);
        _collection = Objects.requireNonNull(collection, "collection");
    }

    public static void main(String[] args) {
        boolean connected = false;
        String url = null;

        if (args.length == 2) {
            if (args[0].equals("-url")) {
                url = args[1];
                connected = true;
            }
        }

        if (!connected) {
            System.err.println("db_mongo_manager: Not connected to MongoDB because of bad usage:");
            System.err.println("Argument " + args[0] + " " + "-url <path>");
            System.exit(1);
        }

        db_mongo_manager openbexi_mongo = new db_mongo_manager(null, null,
                null, null, null, null, null, null);

    }

    // the login() method below has been created by ChatGPT4 after asking for:
    // Can you provide the java code for the method
    // Object login(String url, String database, String collection, JSONArray cookies) .
    // It is a new method for the db_mongo_manager class which connect to MongoDB and
    // get handle for the private variable "_database" and "_collection" according to the arguments "database" and "collection".
    // please use <dependencies>
    //        <dependency>
    //            <groupId>org.mongodb</groupId>
    //            <artifactId>mongodb-driver-sync</artifactId>
    //            <version>4.5.0</version>
    //        </dependency>
    //    </dependencies>
    // please add javadoc

    @Override
    Object login(String url, JSONArray cookies) {
        return null;
    }

    /**
     * Establishes a connection to a MongoDB database and retrieves handles for the specified
     * database and collection.
     *
     * @param url        the URL of the MongoDB instance to connect to
     * @param database   the name of the database to retrieve a handle for
     * @param collection the name of the collection to retrieve a handle for
     * @param cookies    an optional JSONArray of cookies to use for authentication (not used in this implementation)
     * @return a success message if the connection is established and the handles are retrieved, or an error message
     * if the connection fails
     */
    public Object login(String url, String database, String collection, JSONArray cookies) {
        try {
            // Create a MongoClient instance by connecting to the MongoDB instance at the specified URL
            MongoClient mongoClient = MongoClients.create(url);

            // Get a handle to the specified database
            _database = mongoClient.getDatabase(database);

            // Get a handle to the specified collection
            _collection = _database.getCollection(collection);

            // Return a success message
            return "Successfully connected to MongoDB database " + database + " and collection " + collection;
        } catch (Exception e) {
            // Return an error message if the connection fails
            return "Error connecting to MongoDB: " + e.getMessage();
        }
    }

    private static JSONObject createJsonObjectWithKey(Object key, Object value) {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put(key.toString(), value);
        return jsonObject;
    }

    public static JSONArray convertJsonObjectToJsonArray(JSONObject jsonObject) {
        JSONArray jsonArray = new JSONArray();

        for (Object key : jsonObject.keySet()) {
            Object value = jsonObject.get(key);

            if (value instanceof JSONObject) {
                JSONObject nestedObject = (JSONObject) value;
                jsonArray.add(createJsonObjectWithKey(key, convertJsonObjectToJsonArray(nestedObject)));
            } else {
                jsonArray.add(createJsonObjectWithKey(key, value));
            }
        }

        return jsonArray;
    }

    static public JSONObject convertBsonToJson(Document bsonDocument) {
        JSONObject jsonObject = new JSONObject();
        for (String key : bsonDocument.keySet()) {
            Object value = bsonDocument.get(key);
            if (value instanceof Document) {
                jsonObject.put(key, convertBsonToJson((Document) value));
            } else if (value instanceof Iterable) {
                JSONArray jsonArray = new JSONArray();
                for (Object element : (Iterable<?>) value) {
                    if (element instanceof Document) {
                        jsonArray.add(convertBsonToJson((Document) element));
                    } else {
                        jsonArray.add(element);
                    }
                }
                jsonObject.put(key, jsonArray);
            } else {
                jsonObject.put(key, value);
            }
        }
        return jsonObject;
    }

    @Override
    public Object getData(String filter, String ob_scene) {
        JSONArray json_array = new JSONArray();
        try (MongoCursor<Document> cursor = _collection.find().iterator()) {
            while (cursor.hasNext()) {
                Document doc = cursor.next();
                // Preserve reads of the historical aggregate format without rewriting it.
                if (doc.get("0") instanceof Document aggregate) {
                    json_array.addAll(convertJsonObjectToJsonArray(convertBsonToJson(aggregate)));
                } else {
                    json_array.add(convertBsonToJson(doc));
                }
            }
        } catch (MongoException e) {
            System.err.println("Error reading data from MongoDB: " + e.getMessage());
        }
        return json_array;
    }

    @Override
    boolean sendData(Object data) {
        return false;
    }

    @Override
    JSONArray filterDates(JSONArray events, long currentEndDate, long currentStartDate) {
        return null;
    }

    @Override
    JSONArray filterEvents(JSONArray events, String filter_include, String filter_exclude) {
        return null;
    }

    @Override
    JSONArray searchEvents(JSONArray events, String search) {
        return null;
    }

    /**
     * Adds the specified events to the MongoDB collection.
     *
     * @param events event objects with stable id/_id fields, optionally inside an events envelope
     * @return true if the events are added successfully, or false if an error occurs;
     *         a server-side failure can partially apply a batch (no transaction is implied)
     */
    @Override
    public boolean addEvents(JSONArray events, String ob_scene) {
        try {
            List<Document> records = eventDocuments(events);
            if (records.isEmpty()) return true;
            // Each event is independent. Mongo's unique _id prevents accidental replacement.
            for (Document record : records) {
                if (!record.containsKey("_id")) record.put("_id", record.get("id"));
            }
            _collection.insertMany(records);
            return true;
        } catch (Exception e) {
            System.err.println("Cannot add MongoDB events: " + e.getClass().getSimpleName());
            return false;
        }
    }

    public boolean updateEvents(JSONArray events, String ob_scene) {
        try {
            List<Document> records = eventDocuments(events);
            boolean matched = true;
            for (Document record : records) {
                matched &= _collection.replaceOne(eventSelector(record), record).getMatchedCount() == 1;
            }
            return matched;
        } catch (Exception e) {
            System.err.println("Cannot update MongoDB events: " + e.getClass().getSimpleName());
            return false;
        }
    }

    @Override
    public boolean removeEvents(JSONArray events, String ob_scene) {
        try {
            List<Document> records = eventDocuments(events);
            for (Document record : records) _collection.deleteOne(eventSelector(record));
            return true;
        } catch (Exception e) {
            System.err.println("Cannot remove MongoDB events: " + e.getClass().getSimpleName());
            return false;
        }
    }

    /** Validate the entire batch before the first mutation; selectors always contain a scalar ID. */
    private static List<Document> eventDocuments(JSONArray events) {
        if (events == null) throw new IllegalArgumentException("Events must be an array");
        List<Document> records = new ArrayList<>();
        for (Object value : events) {
            if (!(value instanceof JSONObject object)) {
                throw new IllegalArgumentException("Events must contain objects with stable IDs");
            }
            if (object.get("events") instanceof JSONArray nested && !object.containsKey("id") && !object.containsKey("_id")) {
                records.addAll(eventDocuments(nested));
            } else {
                Document record = Document.parse(object.toJSONString());
                eventSelector(record);
                records.add(record);
            }
        }
        Set<Object> identifiers = new HashSet<>();
        for (Document record : records) {
            Object id = record.containsKey("_id") ? record.get("_id") : record.get("id");
            if (!identifiers.add(id)) throw new IllegalArgumentException("Duplicate event ID");
        }
        return records;
    }

    private static Document eventSelector(Document event) {
        String key = event.containsKey("_id") ? "_id" : "id";
        Object id = event.get(key);
        if (!(id instanceof String text && !text.isBlank()) && !(id instanceof Number) && !(id instanceof ObjectId)) {
            throw new IllegalArgumentException("A scalar event id or _id is required");
        }
        // $eq prevents any value from being interpreted as a Mongo query operator.
        return new Document(key, new Document("$eq", id));
    }

    @Override
    public Object addFilter(String ob_timeline_name, String ob_title, String ob_scene, String ob_namespace,
                            String ob_filter_name, String ob_backgroundColor, String ob_user, String ob_email,
                            String ob_top, String ob_left, String ob_width, String ob_height, String ob_camera,
                            String ob_sort_by, String ob_filter) {
        return updateFilter("addFilter", ob_timeline_name, ob_scene, ob_namespace, ob_title, ob_filter_name,
                ob_backgroundColor, ob_user, ob_email, ob_top, ob_left, ob_width, ob_height, ob_camera, ob_sort_by,
                ob_filter);
    }

    @Override
    public Object updateFilter(String ob_action, String ob_timeline_name, String ob_scene, String ob_namespace,
                               String ob_title, String ob_filter_name, String ob_backgroundColor, String ob_user,
                               String ob_email, String ob_top, String ob_left, String ob_width, String ob_height,
                               String ob_camera, String ob_sort_by, String ob_filter) {
        return super.updateFilter(ob_action, ob_timeline_name, ob_scene, ob_namespace, ob_title, ob_filter_name,
                ob_backgroundColor, ob_user, ob_email, ob_top, ob_left, ob_width, ob_height, ob_camera, ob_sort_by, ob_filter);
    }

    @Override
    public Object removeFilter(String ob_timeline_name, String ob_filter_name, String ob_scene, String ob_namespace,
                               String ob_user) {
        return super.removeFilter(ob_timeline_name, ob_filter_name, ob_scene, ob_namespace, ob_user);
    }

    @Override
    public boolean removeAllFilter(String ob_timeline_name, String ob_user) {
        return super.removeAllFilter(ob_timeline_name, ob_user);
    }

    @Override
    boolean onDataChange(String ob_scene) throws InterruptedException {
        return false;
    }

    // ChatGPT4 provided the code for the functions:
    //      - jsonArrayToDocument
    //      - jsonObjectToDocument
    //
    //List of questions:
    //Provide a public java code function to convert  JSONArray to MongoDB document.
    //Rewrite the code using import org.json.simple.JSONArray and org.json.simple.JSONObject
    //
    //This code recursively converts nested JSON objects and arrays to MongoDB documents.
    // Note that it assumes that all values in the JSON array are JSON objects.
    // If your input can include other types of values, you may need to add additional type checks or error handling.
    //
    // This code uses the jsonArrayToDocument method to convert a JSONArray to a Document,
    // and the jsonObjectToDocument method to convert a JSONObject to a Document.
    // Both methods use recursion to handle nested JSON objects and arrays.
    public Document jsonArrayToDocument(JSONArray jsonArray) {
        Document document = new Document();
        for (int i = 0; i < jsonArray.size(); i++) {
            Object obj = jsonArray.get(i);
            if (obj instanceof JSONArray) {
                document.append(String.valueOf(i), jsonArrayToDocument((JSONArray) obj));
            } else if (obj instanceof JSONObject) {
                document.append(String.valueOf(i), jsonObjectToDocument((JSONObject) obj));
            } else {
                document.append(String.valueOf(i), obj);
            }
        }
        return document;
    }

    // ChatGPT4 provided the code for documentToJsonArray:

    public Document jsonObjectToDocument(JSONObject jsonObject) {
        Document document = new Document();
        for (Object keyObj : jsonObject.keySet()) {
            String key = (String) keyObj;
            Object value = jsonObject.get(key);
            if (value instanceof JSONArray) {
                document.append(key, jsonArrayToDocument((JSONArray) value));
            } else if (value instanceof JSONObject) {
                document.append(key, jsonObjectToDocument((JSONObject) value));
            } else {
                document.append(key, value);
            }
        }
        return document;
    }

    /**
     * Converts a MongoDB Document object to a JSONArray using the org.json.simple library.
     *
     * @param doc the Document object to convert
     * @return a JSONArray containing the converted data
     */

    public JSONArray documentToJsonArray(Document doc) {
        JSONArray jsonArray = new JSONArray();
        JSONObject jsonObject = new JSONObject();
        jsonArray.add(jsonObject);
        return jsonArray;
    }

    /**
     * Converts a JSON string to a JSONArray using the org.json.simple library.
     *
     * @param jsonString the JSON string to convert
     * @return a JSONArray containing the converted data
     * @throws ParseException if the JSON string cannot be parsed
     */
    public JSONArray jsonStringToJsonArray(String jsonString) throws ParseException {
        JSONParser parser = new JSONParser();
        Object obj = parser.parse(jsonString);
        if (obj instanceof JSONObject) {
            JSONArray jsonArray = new JSONArray();
            jsonArray.add(obj);
            return jsonArray;
        }
        JSONArray jsonArray = (JSONArray) obj;
        return jsonArray;
    }

}

