let ob_texture = new Map();
// global texture
ob_texture.set("icon/ob_error.png", new THREE.TextureLoader().load("icon/ob_error.png"));
ob_texture.set("icon/ob_warning.png", new THREE.TextureLoader().load("icon/ob_warning.png"));
ob_texture.set("icon/ob_info.png", new THREE.TextureLoader().load("icon/ob_info.png"));
ob_texture.set("icon/ob_start.png", new THREE.TextureLoader().load("icon/ob_start.png"));
ob_texture.set("icon/ob_stop.png", new THREE.TextureLoader().load("icon/ob_stop.png"));
ob_texture.set("icon/ob_check_failed.png", new THREE.TextureLoader().load("icon/ob_check_failed.png"));
ob_texture.set("icon/ob_check_aborted.png", new THREE.TextureLoader().load("icon/ob_check_aborted.png"));
ob_texture.set("icon/ob_check_ok.png", new THREE.TextureLoader().load("icon/ob_check_ok.png"));
ob_texture.set("icon/ob_check_warning.png", new THREE.TextureLoader().load("icon/ob_check_warning.png"));
ob_texture.set("icon/ob_phone.png", new THREE.TextureLoader().load("icon/ob_phone.png"));
ob_texture.set("icon/ob_bug.png", new THREE.TextureLoader().load("icon/ob_bug.png"));
ob_texture.set("icon/ob_lost_connection.png", new THREE.TextureLoader().load("icon/ob_lost_connection.png"));
ob_texture.set("icon/ob_swap.png", new THREE.TextureLoader().load("icon/ob_swap.png"));
ob_texture.set("icon/ob_gate_open.png", new THREE.TextureLoader().load("icon/ob_gate_open.png"));
ob_texture.set("icon/ob_gate_close.png", new THREE.TextureLoader().load("icon/ob_gate_close.png"));
ob_texture.set("icon/ob_red_flag.png", new THREE.TextureLoader().load("icon/ob_red_flag.png"));
ob_texture.set("icon/ob_green_flag.png", new THREE.TextureLoader().load("icon/ob_green_flag.png"));
ob_texture.set("icon/ob_yellow_flag.png", new THREE.TextureLoader().load("icon/ob_yellow_flag.png"));
ob_texture.set("icon/ob_orange_flag.png", new THREE.TextureLoader().load("icon/ob_orange_flag.png"));
ob_texture.set("icon/ob_yellow_square.png", new THREE.TextureLoader().load("icon/ob_yellow_square.png"));
ob_texture.set("icon/ob_orange_square.png", new THREE.TextureLoader().load("icon/ob_orange_square.png"));
ob_texture.set("icon/ob_red_square.png", new THREE.TextureLoader().load("icon/ob_red_square.png"));
ob_texture.set("icon/ob_purple_square.png", new THREE.TextureLoader().load("icon/ob_purple_square.png"));
ob_texture.set("icon/ob_green_square.png", new THREE.TextureLoader().load("icon/ob_green_square.png"));
ob_texture.set("icon/ob_blue_square.png", new THREE.TextureLoader().load("icon/ob_blue_square.png"));
ob_texture.set("icon/ob_script.png", new THREE.TextureLoader().load("icon/ob_script.png"));
ob_texture.set("icon/ob_crontab.png", new THREE.TextureLoader().load("icon/ob_crontab.png"));
ob_texture.set("icon/ob_clock.png", new THREE.TextureLoader().load("icon/ob_clock.png"));
ob_texture.set("icon/ob_info2.png", new THREE.TextureLoader().load("icon/ob_info2.png"));
ob_texture.set("icon/ob_delete.png", new THREE.TextureLoader().load("icon/ob_delete.png"));
ob_texture.set("icon/ob_yellow_ring.png", new THREE.TextureLoader().load("icon/ob_yellow_ring.png"));


// Satellite/Communication texture
ob_texture.set("icon/ob_connect.png", new THREE.TextureLoader().load("icon/ob_connect.png"));
ob_texture.set("icon/ob_no_connect.png", new THREE.TextureLoader().load("icon/ob_no_connect.png"));
ob_texture.set("icon/ob_satellite.png", new THREE.TextureLoader().load("icon/ob_satellite.png"));
ob_texture.set("icon/ob_no_satellite.png", new THREE.TextureLoader().load("icon/ob_no_satellite.png"));
ob_texture.set("icon/ob_no_tlm_red.png", new THREE.TextureLoader().load("icon/ob_no_tlm_red.png"));
ob_texture.set("icon/ob_tlm_red.png", new THREE.TextureLoader().load("icon/ob_tlm_red.png"));
ob_texture.set("icon/ob_tlm_green.png", new THREE.TextureLoader().load("icon/ob_tlm_green.png"));
ob_texture.set("icon/ob_tlm_orange.png", new THREE.TextureLoader().load("icon/ob_tlm_orange.png"));
